Make indexers work for interface objects
pythonnet/pythonnet pull request #1246
Opened 2020-10-05 13:38 UTC by danabr

### What does this implement/fix? Explain your changes.

Makes the following work instead of throwing an exception:

```python
from System.Collections.Generic import Dictionary, IDictionary
d = IDictionary[str, str](Dictionary[str, str]())
d["one"] = "1"
assert d["one"] == "1"

### Does this close any currently open issues?

No

### Checklist

Check all those that are applicable and complete.

-   [X] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [ ] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [X] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

2020-10-05 16:22 UTC, lostmsu requested changes
Two things related to each other:
1. Please, add a negative test (if one does not exist yet). E.g. construct an empty `System.Object`, and ensure Python can't index it for read or write.
2. Consider only assigning `mp*_subscript` slots only when the type actually supports indexing like you did with `tp_next`.

2020-10-06 05:37 UTC, danabr commented
I've added the two things you asked for.

The erasing of the slots is ugly. We should consider moving `InitializeSlots` into `ManagedObject` and its descendants instead, so that you would just do `impl.InitializeSlots(type)`, and each type could handle its own initialization.

2020-10-06 17:32 UTC, lostmsu approved these changes

2020-10-06 17:38 UTC, lostmsu commented
Great, thanks!

I agree on `InitializeSlots`. If you'd like to work on that, you can start with a draft request demonstrating an approach for any one kind of `ManagedObject` (it does not have to pass tests or compile). Otherwise we'll just keep that in mind.

Overall it might make sense to move the majority of `TypeManager` type creation functionality into `ManagedObject` and deriving classes, including `PyType` construction. But we better do that along with the migration to `PyType_FromSpec`.

2020-10-06 17:38 UTC, merged