Add a failing test for Unicode conversion
pythonnet/pythonnet pull request #1467
Opened 2021-06-08 12:41 UTC by pkese

### What does this implement/fix? Explain your changes.

A failing test for #1466

### Does this close any currently open issues?

No, just analyzes failure case.

### Any other comments?

See #1466

### Checklist

Check all those that are applicable and complete.

-   [ ] Make sure to include one or more tests for your change
-   [ ] If an enhancement PR, please create docs and at best an example
-   [ ] Add yourself to [`AUTHORS`](../blob/master/AUTHORS.md)
-   [ ] Updated the [`CHANGELOG`](../blob/master/CHANGELOG.md)

2021-06-08 12:41 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/pythonnet/pythonnet?pullRequest=1467) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/pythonnet/pythonnet?pullRequest=1467) before we can accept your contribution.<br/><br/>:x: pkese [sign now](https://cla.dotnetfoundation.org/pythonnet/pythonnet?pullRequest=1467)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/pythonnet/pythonnet?pullRequest=1467) it.</sub>

2021-06-09 08:10 UTC, lostmsu requested changes

2021-06-09 08:10 UTC, lostmsu commented on src/runtime/runtime.cs
> +                    new IntPtr(value.Length * sizeof(Char)),
We're in C# 9 now, so we can use `nint` instead of `IntPtr` for `ssize_t`

2021-06-09 08:10 UTC, lostmsu commented on src/runtime/runtime.cs
> +                ).DangerousGetAddress();
Better use `DangerousMoveToPointer` or `DangerousMoveToPointerOrNull`

2021-06-09 08:10 UTC, lostmsu commented
@filmor requested some minor tweaks

2021-06-09 16:44 UTC, pkese commented on CHANGELOG.md
> +-   Unicode strings with surrogates get truncated when converting from Python
Thanks, I've applied the suggested change in today's commit.

2021-06-11 09:36 UTC, lostmsu commented on src/runtime/runtime.cs
> +                char* codePoints = (char*)PyBytes_AsString(bytesPtr);
NIT: better add overload for `PyBytes_AsString` that takes `BorrowedReference`. This would remove unnecessary call to `DangerousGetAddress` above.

2021-06-11 09:42 UTC, lostmsu commented
@filmor it did not fail on rerun. I think we can merge this in, and investigate if it will reappear.

2021-06-11 09:42 UTC, lostmsu approved these changes

2021-06-11 10:12 UTC, merged